services:
  - type: web
    name: text-to-course-api
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URL
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: AUTH0_ISSUER
        sync: false
      - key: AUTH0_AUDIENCE
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: CLAUDE_API_KEY
        sync: false
